### ISSUE TITLE
Add staging deployment for L0 in Cloud Run

### ISSUE THREAD

**Issue by KevinDyer** [graffiticode/L0#22]

**Comment by KevinDyer** [comment]
Add domain mapping once service is available

**Comment by KevinDyer** [comment]
This is ready for a domain mapping in [Cloud Run](https://console.cloud.google.com/run/detail/us-central1/l0-staging/metrics?cloudshell=false&project=graffiticode)

**Comment by jeffdyer** [comment]
Done.
